# Generated by Django 5.1.1 on 2025-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
